# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-20 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='request_number',
            field=models.CharField(default='', max_length=10, unique=True),
        ),
    ]
