# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-06 15:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipv4_address', models.GenericIPAddressField(default='0.0.0.0', protocol='ipv4')),
                ('message', models.CharField(default='N/A', max_length=255)),
                ('date', models.CharField(default='01/01/1970', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipv4_address', models.GenericIPAddressField(protocol='ipv4', unique=True)),
                ('host_name', models.CharField(max_length=80)),
                ('os', models.CharField(default='', max_length=50)),
                ('lsp', models.CharField(default='', max_length=50)),
                ('location', models.CharField(default='', max_length=25)),
                ('tags', models.CharField(default='', max_length=50)),
                ('host_groups', models.CharField(default='', max_length=125)),
                ('notes', models.CharField(default='', max_length=320)),
                ('ports', models.TextField(default='')),
            ],
            options={
                'permissions': (('edit_host', 'Can edit host information'),),
            },
        ),
        migrations.CreateModel(
            name='HostVisits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipv4_address', models.GenericIPAddressField(protocol='ipv4')),
                ('visits', models.IntegerField(default=0)),
                ('user', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subnet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipv4_address', models.CharField(default='0.0.0', max_length=11, unique=True)),
                ('suffix', models.CharField(default='.x', max_length=2)),
            ],
        ),
    ]
