# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-28 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipv4_address', models.GenericIPAddressField(protocol='ipv4', unique=True)),
                ('host_name', models.CharField(max_length=80)),
                ('os', models.CharField(default='', max_length=50)),
                ('lsp', models.CharField(default='', max_length=50)),
                ('location', models.CharField(default='', max_length=25)),
                ('tags', models.CharField(default='', max_length=50)),
                ('host_groups', models.CharField(default='', max_length=125)),
                ('notes', models.CharField(default='', max_length=320)),
                ('ports', models.TextField(default='')),
            ],
            options={
                'permissions': (('edit_host', 'Can edit host information'),),
            },
        ),
        migrations.CreateModel(
            name='Subnet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipv4_address', models.GenericIPAddressField(default='0.0.0', protocol='ipv4', unique=True)),
                ('suffix', models.CharField(default='.x', max_length=2)),
            ],
        ),
    ]
