# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-24 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipv4_address', models.GenericIPAddressField(default='0.0.0.0', protocol='ipv4', unique=True)),
                ('host_name', models.CharField(max_length=80)),
                ('os', models.CharField(default='', max_length=50)),
                ('lsp', models.CharField(default='', max_length=50)),
                ('location', models.CharField(default='', max_length=25)),
                ('tags', models.CharField(default='', max_length=50)),
                ('host_groups', models.CharField(default='', max_length=125)),
                ('notes', models.CharField(default='', max_length=320)),
            ],
        ),
        migrations.CreateModel(
            name='Subnet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipv4_address', models.GenericIPAddressField(default='0.0.0.0', protocol='ipv4', unique=True)),
                ('prefix', models.IntegerField()),
            ],
        ),
    ]
