# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-26 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='ports',
            field=models.TextField(default=''),
        ),
    ]
