# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 20:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0002_auto_20170227_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subnet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipv4_address', models.GenericIPAddressField(default='0.0.0.0', protocol='ipv4')),
                ('suffix', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='host',
            name='subnet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hosts.Subnet'),
        ),
    ]
