# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 17:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0003_auto_20170227_1555'),
    ]

    operations = [
        migrations.RenameField(
            model_name='host',
            old_name='name',
            new_name='host_name',
        ),
    ]
