# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 19:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0004_auto_20170228_1227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subnet',
            old_name='suffix',
            new_name='prefix',
        ),
    ]
