# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 18:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0005_auto_20170322_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='subnet',
        ),
        migrations.AddField(
            model_name='subnet',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hosts.Host'),
        ),
    ]
