# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 17:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0006_auto_20170330_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subnet',
            name='host',
        ),
    ]
