# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-18 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0007_remove_subnet_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='host_groups',
            field=models.CharField(default='', max_length=125),
        ),
        migrations.AddField(
            model_name='host',
            name='location',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='host',
            name='lsp',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='host',
            name='notes',
            field=models.CharField(default='', max_length=320),
        ),
        migrations.AddField(
            model_name='host',
            name='os',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='host',
            name='tags',
            field=models.CharField(default='', max_length=50),
        ),
    ]
