# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-20 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0008_auto_20170418_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='ipv4_address',
            field=models.GenericIPAddressField(default='0.0.0.0', protocol='ipv4', unique=True),
        ),
        migrations.AlterField(
            model_name='subnet',
            name='ipv4_address',
            field=models.GenericIPAddressField(default='0.0.0.0', protocol='ipv4', unique=True),
        ),
    ]
