# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-02 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=80, unique=True)),
                ('secret', models.CharField(max_length=80)),
            ],
        ),
    ]
