# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-10 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScanType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_name', models.CharField(default='My Custom Scan', max_length=255)),
                ('host_address', models.CharField(default='0.0.0.0', max_length=19)),
                ('ports', models.CharField(max_length=255)),
                ('scan_options', models.CharField(max_length=255)),
            ],
        ),
    ]
