# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-19 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plugin_id', models.CharField(default='', max_length=10)),
                ('plugin_name', models.CharField(default='', max_length=50)),
                ('severity', models.CharField(default='', max_length=10)),
                ('ipv4_address', models.GenericIPAddressField(default='0.0.0.0', protocol='ipv4')),
                ('host_name', models.CharField(max_length=80)),
            ],
        ),
    ]
