# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-20 19:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vulnerabilities', '0002_auto_20170420_1424'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vulnerability',
            unique_together=set([('plugin_id', 'ipv4_address')]),
        ),
    ]
