# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-20 19:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vulnerabilities', '0003_auto_20170420_1425'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vulnerability',
            unique_together=set([]),
        ),
    ]
